// REDUX ACTION TYPES
export const GET_LIST_STUDIO_ERROR = 'GET_LIST_STUDIO_ERROR'
export const GET_LIST_STUDIO_SUCCESS = 'GET_LIST_STUDIO_SUCCESS'
export const GET_LIST_STUDIO_LOADING = 'GET_LIST_STUDIO_LOADING'

export const SCROLL_TO_SEC_2 = 'SCROLL_TO_SEC_2'
export const SCROLL_TO_ID = 'SCROLL_TO_ID'
